version: "2.6"

volumes:
  storage_data:

services:
  database:
    image: postgres:14.3-alpine
    env_file: ./micro_services/storage/.env
    restart: unless-stopped
    volumes:
      - storage_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"